### PR TITLE
Bug/1202189506746355 broken pipe more log

### PR DESCRIPTION
**Pull request by sfffaaa**
Logging more to find the root cause

### CODE REVIEW

**Comment by niazhussain** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **marynashevchuk**
You can assign the PR to them by writing `/assign @marynashevchuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=peaqnetwork%2Fpeaq-network-ev-charging-sim-be).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-be/blob/dev/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by niazhussain** [comment]
:star: PR built and available in a preview **peaqnetwork-peaq-network-ev-charging-sim-be-pr-44** [here](http://peaq-network-ev-charging-sim-be-pr44.ci.peaq.network)

**Review by irediaes — APPROVED** [review]

**Comment by niazhussain** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *[irediaes](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-be/pull/44#pullrequestreview-956108779 "Approved")*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **marynashevchuk**
You can assign the PR to them by writing `/assign @marynashevchuk` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=peaqnetwork%2Fpeaq-network-ev-charging-sim-be).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-be/blob/dev/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by niazhussain** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[irediaes](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-be/pull/44#pullrequestreview-956108779 "Approved")*, *[Veleslavskiy](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-be/pull/44#issuecomment-1113147331 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=peaqnetwork%2Fpeaq-network-ev-charging-sim-be).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-be/blob/dev/OWNERS)~~ [Veleslavskiy]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by niazhussain** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *[irediaes](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-be/pull/44#pullrequestreview-956108779 "Approved")*, *[Veleslavskiy](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-be/pull/44#issuecomment-1113147331 "Approved")*

The full list of commands accepted by this bot can be found [here](https://jenkins-x.io/v3/develop/reference/chatops/?repo=peaqnetwork%2Fpeaq-network-ev-charging-sim-be).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/peaqnetwork/peaq-network-ev-charging-sim-be/blob/dev/OWNERS)~~ [Veleslavskiy]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
